# theme = "mangooscheme"
theme = "horizon-dark_custom"

[editor]
line-number = "relative"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
# display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner","diagnostics"]
center = ["file-modification-indicator","file-name","version-control"]
right = ["selections","register","position","file-encoding"]

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]

[keys.insert]
C-p = "signature_help"
