[[language]]
name = "rust"
file-types = ["rs"]
language-servers = ["rust-analyzer"]

[language-server.rust-analyzer]
command = "rust-analyzer"

#################### GAME DEV #################### 
[language-server.godot]
command = "ncat" 
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = [ "godot" ]
##################################################

#################### WEB DEV #####################

# [language-server.tailwindcss-ls]
# command = "tailwindcss-language-server"
# args = ["--stdio"]

# [language-server.emmet-ls]
# command = "emmet-ls"
# args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser","html"]}
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser","css"]}
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "vscode-eslint-language-server"]
formatter = { command = "prettier", args = ["--parser","typescript"]}
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls", "vscode-eslint-language-server"]
formatter = { command = "prettier", args = ["--parser","typescript"]}
auto-format = true
#################### OTHERS #####################
[[language]]
name = "lua"
language-servers = ["lua-language-server"]
formatter = { command = "stylua" ,args=["-"]}
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
