# Syntax
"attribute" = {fg = "light_blue"}
"tag" = {fg = "purple"}
"keyword" = {fg = "purple"}
"variable" = {fg = "pink"}
"function" = {fg = "light_blue"}
"constructor" = {fg = "orange_2"}
"type" = {fg = "orange_2"}
"namespace" = { fg = "orange_2", modifiers = ["bold", "italic"]}
"constant" ={ fg = "light_purple"}
"string" = {fg = "teal"}
"operator" = {fg = "teal"}
"punctuation" = {fg = "cherry_pink"}

# UI
"ui.background" = {bg = "bg"}
"ui.selection" = {bg = "selection",underline = {style = "dashed"}}
"ui.cursor" = { fg = "purple", bg = "light_blue"}
"ui.cursor.primary" = { fg = "light_blue", bg = "purple"}
"ui.linenr" = {fg = "light_blue"}
"ui.linenr.selected" = {fg = "purple"}
"ui.virtual.jump-label" = {fg = "orange_2", modifiers = ["bold"]}
"ui.virtual.inlay-hint" = {modifiers = ["bold","italic"]}
"ui.bufferline" = {fg = "purple"}
"ui.bufferline.active" = {bg = "test", underline = {style = "curl"}}
"ui.statusline" = {fg = "purple",bg = "test"}

# Git Diffs
"diff.plus" = {fg = "teal"}
"diff.minus" = {fg = "cherry_pink"}
"diff.delta" = {fg = "light_blue"}

# Diagnostics
"error" = {fg = "cherry_pink"}
"warning" = {fg = "orange_2"}
"info" = {fg = "teal"}
"hint" = {fg = "light_blue"}
"diagnostic.error" = { underline  ={color = "cherry_pink", style = "curl"}}
"diagnostic.warning" = { underline  ={color = "orange_2", style = "curl"}}
"diagnostic.info" = { underline  ={color = "teal", style = "curl"}}
"diagnostic.hint" = { underline  ={color = "light_blue", style = "curl"}}

# Markup
"markup.heading" = "purple"
"markup.quote" = "cherry_pink"
"markup.link" = "light_blue"
"markup.raw" = "cherry_pink"
"markup.bold" = {modifiers = ["bold"]}
"markup.italic" = {modifiers = ["italic"]}
"markup.strikethrough" = {modifiers = ["crossed_out"]}

[palette]
bg = "#1c1431"
purple = "#8d15e3"
light_purple = "#7d66df"
pink = "#b849a7"
orange = "#f7964c"
orange_2 = "#FCA17D"
light_blue = "#48afff"
green = "#00ff7f"
teal = "#7DE6B7"
cherry_pink = "#da627d"
selection = "#353747"
test = "#19122B"


